version: '3'
services:
  db:
    image: "postgres:9.6.5"
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    env_file:
      - config.env

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server
    volumes:
      - './data/redis:/data'

  app:
    build: .
    command: ./utils/run.sh
    env_file:
      - config.env
    ports:
      - 5123:5123
    volumes:
      - "./data/uploads:/home/cdb/app/public/uploads"
      - "./app:/home/cdb/appsrc"
      - "./migrations:/home/cdb/migrations"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A app.tasks.celery worker
    env_file:
      - config.env
    environment:
      - FLASK_CONFIG=../config.cfg
    volumes:
      - "./data/uploads:/home/cdb/app/public/uploads"
    depends_on:
      - redis
